/**
 * @fileoverview Wompi Payment Gateway Integration (Server Actions)
 * Handles secure, server-side cryptographic operations required by the Wompi API.
 */

// 'use server' is critical here. It tells Next.js that this file must NEVER
// be bundled with the client-side JavaScript, protecting your secret keys.
"use server";

import crypto from "crypto";

/**
 * Generates a SHA-256 cryptographic signature to validate transaction integrity.
 * Wompi uses this hash to verify that the price and reference ID were not tampered
 * with by a malicious user modifying the frontend code before checkout.
 * * @param {string} reference - The unique order ID generated by Firestore.
 * @param {number} amountInCents - The total purchase amount multiplied by 100 (e.g., $10,000 COP = 1000000).
 * @returns {Promise<string>} The hexadecimal hash string required by the Wompi checkout widget.
 * @throws {Error} If the server environment is missing the Wompi secret.
 */
export async function getWompiSignature(
  reference: string,
  amountInCents: number,
) {
  // Pull the secret key directly from the secure Node environment
  const secret = process.env.WOMPI_INTEGRITY_SECRET;

  // Failsafe: Prevent checkout from initializing if the environment is misconfigured
  if (!secret) {
    throw new Error("Falta WOMPI_INTEGRITY_SECRET en las variables de entorno");
  }

  /**
   * CONCATENATION RULE:
   * Wompi requires the raw string to be constructed in this exact, specific order:
   * 1. Reference ID
   * 2. Amount in Cents
   * 3. Currency Code (Strictly 'COP')
   * 4. Integrity Secret
   */
  const concatenatedString = `${reference}${amountInCents}COP${secret}`;

  /**
   * HASHING PROCESS:
   * We use Node's native 'crypto' module to create a one-way SHA-256 hash of the string,
   * then output it as a hexadecimal format string which is what Wompi expects.
   */
  const hashHex = crypto
    .createHash("sha256")
    .update(concatenatedString)
    .digest("hex");

  return hashHex;
}
